### ISSUE TITLE
No chart displayed

### ISSUE THREAD

**Issue by saporator** [ma4nn/moneymoney-sankey#2]
Hi,

the generated html page doesn't show a chart. There is a header and footer, a section to adjust the chart (but also here no furtehr entries). I copied the css file and 2 ts files into the folder of the html file but no change.
What do I need to do to ge the chart displayed?

Thank you

**Comment by ma4nn** [comment]
Hi @saporator,

thanks for your report and sorry that you are experiencing issues.

Can you please try to play a little bit with the exported transactions (e.g. filter another category, etc.) to check if it is perhaps related to some transactions only?
If that does not help can you send me an (anonymized/sample) HTML export file for which the error occurs so that I can have a look?

BTW: you only need to copy the [SankeyChart.lua](https://github.com/ma4nn/moneymoney-sankey/releases/download/v1.0.0/SankeyChart.lua) from the release, this file already contains everything.

Looking forward to your feedback!

Best regards

**Comment by saporator** [comment]
Hi,
I'm still trying to get something. I also try to insert some print statements into your coding. I hope that's fine. It seems that transactions are read. There are also some numbers now in the source code of the html page (but still no chart). I also exported only 1-2 categories: result empty file.

I have the feeling that I need to setup my categories maybe in a different way (I have many and up to three levels)? Do I need to set a budget for every category in order to get it working? 

I continue to play arround and will send you a file to your mail address which I found on your web page (I don't know how to send a file here in github).

Thank you

**Comment by ma4nn** [comment]
> I have the feeling that I need to setup my categories maybe in a different way (I have many and up to three levels)?

Sure, it may definitely have many reasons why the page is empty. As the script is quite new it may be that there are category setups that need some bugfixing. But basically the script limits the category depth to 3, so that alone should not be a problem.

> Do I need to set a budget for every category in order to get it working?

No budgets are not relevant.

**Comment by saporator** [comment]
[Neues Konto.zip](https://github.com/ma4nn/moneymoney-sankey/files/14096620/Neues.Konto.zip)

I created a new database (offline account) and inserted 3 transactions. At the bottom of the html I see some values.

**Comment by ma4nn** [comment]
@saporator good idea with the offline account👍 
as described in the README you need to download the `SankeyChart.lua` from the [release](https://github.com/ma4nn/moneymoney-sankey/releases/latest/download/SankeyChart.lua), not from the repo as you did

**Comment by saporator** [comment]
Thank you! Sorry for my mistake, I'm not an expert with github and I thought I can downoad it from the list above. 
Now it works fine. I need to now to understand the chart ;-)
